<script setup lang="ts">
import { computed } from 'vue'
import { DownloadOutlined, FileTextOutlined } from '@ant-design/icons-vue'
import { useRoute } from 'vue-router'
import { api } from '@/services/api'
const route = useRoute(); const path = computed(() => String(route.query.path ?? '')); const url = computed(() => api.rawUrl(path.value)); const isHtml = computed(() => /\.html?$/i.test(path.value))
</script>
<template><section class="raw-page"><div><p class="eyebrow">SOURCE MATERIAL</p><h1 class="page-heading">原始资料</h1><p class="page-subheading source-path">{{ path || '请选择要查看的原始资料' }}</p></div><a-alert v-if="!path" type="warning" message="请从检索结果中选择原始资料" show-icon class="notice" /><template v-else><div class="action-row"><a :href="url" target="_blank" rel="noopener"><a-button type="primary"><DownloadOutlined />在新窗口打开</a-button></a><span>原始资料由后端受限提供，阅读页不改写原文件。</span></div><iframe v-if="isHtml" class="preview" :src="url" title="原始 HTML 预览" sandbox="allow-same-origin" /><a-card v-else class="file-notice" :bordered="false"><FileTextOutlined /><div><strong>此文件可在独立窗口中查看或下载</strong><p>支持原始资料的追溯与核验；请通过上方操作打开文件。</p></div></a-card></template></section></template>
<style scoped>.raw-page { padding-top: 14px; }.eyebrow { margin: 0 0 7px; color: #4b7edb; font-size: 11px; font-weight: 700; letter-spacing: 1.2px; }.source-path { font-family: Consolas, monospace; font-size: 12px; }.notice { margin-top: 24px; }.action-row { display: flex; align-items: center; gap: 14px; margin: 25px 0 18px; }.action-row span { color: var(--app-muted); font-size: 13px; }.preview { width: 100%; min-height: 70vh; background: #fff; border: 1px solid var(--app-border); border-radius: 8px; }.file-notice { display: flex; align-items: flex-start; gap: 14px; margin-top: 24px; }.file-notice :deep(.ant-card-body) { display: flex; align-items: flex-start; gap: 14px; }.file-notice :deep(.anticon) { color: #2b68d6; font-size: 25px; }.file-notice p { margin: 5px 0 0; color: var(--app-muted); } @media(max-width:640px) { .action-row { align-items: flex-start; flex-direction: column; } }</style>
