<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { FilterOutlined, SearchOutlined } from '@ant-design/icons-vue'
import { api, type SearchResult } from '@/services/api'
const route = useRoute(); const router = useRouter()
const query = ref(String(route.query.q ?? '')); const domain = ref(String(route.query.domain ?? '')); const kind = ref(String(route.query.kind ?? ''))
const results = ref<SearchResult[]>([]); const total = ref(0); const facets = ref<[string, number][]>([]); const loading = ref(false); const error = ref('')
const lastSearchKey = ref('')
function makeSearchKey() { return [query.value.trim(), domain.value, kind.value].join('\u0000') }
async function run() { if (!query.value.trim()) { lastSearchKey.value = ''; results.value = []; total.value = 0; return }; lastSearchKey.value = makeSearchKey(); loading.value = true; error.value = ''; try { const data = await api.search(query.value.trim(), domain.value, kind.value); results.value = data.results; total.value = data.total; facets.value = data.facets; router.replace({ query: { q: query.value.trim(), ...(domain.value ? { domain: domain.value } : {}), ...(kind.value ? { kind: kind.value } : {}) } }) } catch (reason) { error.value = reason instanceof Error ? reason.message : '检索失败' } finally { loading.value = false } }
watch(() => [route.query.q, route.query.domain, route.query.kind], value => { query.value = String(value[0] ?? ''); domain.value = String(value[1] ?? ''); kind.value = String(value[2] ?? ''); if (query.value.trim() && makeSearchKey() !== lastSearchKey.value) run(); if (!query.value.trim()) { results.value = []; total.value = 0 } }, { immediate: true })
const title = computed(() => query.value ? `找到 ${total.value} 条相关资料` : '输入关键词开始检索')
function open(item: SearchResult) { router.push({ path: item.path.startsWith('wiki/') ? '/document' : '/raw', query: { path: item.path } }) }
</script>
<template><section class="search-page"><div class="search-head"><div><h1 class="page-heading">全文检索</h1><p class="page-subheading">跨知识页面与原始资料检索，结果保留来源路径。</p></div></div><a-card class="search-box" :bordered="false"><a-input-search v-model:value="query" size="large" placeholder="输入关键词，例如：收入确认、函证、独立性" :loading="loading" @search="run"><template #enterButton><SearchOutlined />检索</template></a-input-search><div class="filters"><span><FilterOutlined /> 筛选范围</span><a-select v-model:value="kind" @change="run"><a-select-option value="">全部类型</a-select-option><a-select-option value="wiki">知识页面</a-select-option><a-select-option value="raw">原始资料</a-select-option></a-select><a-select v-model:value="domain" @change="run"><a-select-option value="">全部领域</a-select-option><a-select-option v-for="facet in facets" :key="facet[0]" :value="facet[0]">{{ facet[0] }} ({{ facet[1] }})</a-select-option></a-select></div></a-card><a-alert v-if="error" type="error" :message="error" show-icon class="result-alert" /><section class="result-section"><header><h2>{{ title }}</h2><span v-if="results.length">按相关性排序</span></header><a-spin :spinning="loading"><a-empty v-if="!loading && query && !results.length" description="未找到匹配资料，请更换关键词或筛选条件" /><a-list v-else class="result-list" :data-source="results" item-layout="vertical"><template #renderItem="{ item }"><a-list-item class="result-item" @click="open(item)"><div class="result-top"><a class="result-title">{{ item.title }}</a><a-tag>{{ item.kind === 'wiki' ? '知识页面' : '原始资料' }}</a-tag></div><p class="result-path">{{ item.path }}</p><p class="result-snippet">{{ item.snippet }}</p><a-space size="small"><a-tag v-if="item.answer_ready" color="green">可用于答疑</a-tag><a-tag v-if="item.domain">{{ item.domain }}</a-tag><a-tag v-if="item.maturity">{{ item.maturity }}</a-tag></a-space></a-list-item></template></a-list></a-spin></section></section></template>
<style scoped>.search-head { margin: 14px 0 20px; }.search-box { box-shadow: var(--app-shadow); }.search-box :deep(.ant-card-body) { padding: 20px; }.filters { display: flex; align-items: center; gap: 10px; margin-top: 15px; }.filters > span { color: var(--app-muted); font-size: 13px; }.filters :deep(.ant-select) { width: 160px; }.result-alert { margin-top: 18px; }.result-section { margin-top: 24px; }.result-section header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 10px; }.result-section h2 { margin: 0; font-size: 16px; }.result-section header span { color: var(--app-muted); font-size: 12px; }.result-list { background: var(--app-surface); border: 1px solid var(--app-border); border-radius: 8px; box-shadow: var(--app-shadow); overflow: hidden; }.result-item { padding: 20px 22px !important; cursor: pointer; transition: background .18s; }.result-item:hover { background: var(--app-accent-soft); }.result-top { display: flex; align-items: center; gap: 10px; }.result-title { color: var(--app-text); font-size: 16px; font-weight: 700; }.result-path { margin: 6px 0; overflow: hidden; color: var(--app-muted); font-family: Consolas, monospace; font-size: 12px; text-overflow: ellipsis; white-space: nowrap; }.result-snippet { margin: 8px 0 12px; color: var(--app-muted); line-height: 1.75; }.result-snippet :deep(mark) { color: #1a57bf; background: #dceaff; }.result-top :deep(.ant-tag) { margin-left: auto; } @media(max-width:640px) { .filters { align-items: stretch; flex-wrap: wrap; }.filters > span { width: 100%; }.filters :deep(.ant-select) { flex: 1; min-width: 130px; }.result-item { padding: 16px !important; } }</style>
